// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "go-challenge-agenda/services/agenda/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BlockedSlotRepository is an autogenerated mock type for the BlockedSlotRepository type
type BlockedSlotRepository struct {
	mock.Mock
}

type BlockedSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockedSlotRepository) EXPECT() *BlockedSlotRepository_Expecter {
	return &BlockedSlotRepository_Expecter{mock: &_m.Mock}
}

// CreateBlockedSlot provides a mock function with given fields: ctx, b
func (_m *BlockedSlotRepository) CreateBlockedSlot(ctx context.Context, b *domain.BlockedSlot) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for CreateBlockedSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlockedSlot) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BlockedSlotRepository_CreateBlockedSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBlockedSlot'
type BlockedSlotRepository_CreateBlockedSlot_Call struct {
	*mock.Call
}

// CreateBlockedSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.BlockedSlot
func (_e *BlockedSlotRepository_Expecter) CreateBlockedSlot(ctx interface{}, b interface{}) *BlockedSlotRepository_CreateBlockedSlot_Call {
	return &BlockedSlotRepository_CreateBlockedSlot_Call{Call: _e.mock.On("CreateBlockedSlot", ctx, b)}
}

func (_c *BlockedSlotRepository_CreateBlockedSlot_Call) Run(run func(ctx context.Context, b *domain.BlockedSlot)) *BlockedSlotRepository_CreateBlockedSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BlockedSlot))
	})
	return _c
}

func (_c *BlockedSlotRepository_CreateBlockedSlot_Call) Return(_a0 error) *BlockedSlotRepository_CreateBlockedSlot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockedSlotRepository_CreateBlockedSlot_Call) RunAndReturn(run func(context.Context, *domain.BlockedSlot) error) *BlockedSlotRepository_CreateBlockedSlot_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlockedSlot provides a mock function with given fields: ctx, id
func (_m *BlockedSlotRepository) DeleteBlockedSlot(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlockedSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BlockedSlotRepository_DeleteBlockedSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlockedSlot'
type BlockedSlotRepository_DeleteBlockedSlot_Call struct {
	*mock.Call
}

// DeleteBlockedSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BlockedSlotRepository_Expecter) DeleteBlockedSlot(ctx interface{}, id interface{}) *BlockedSlotRepository_DeleteBlockedSlot_Call {
	return &BlockedSlotRepository_DeleteBlockedSlot_Call{Call: _e.mock.On("DeleteBlockedSlot", ctx, id)}
}

func (_c *BlockedSlotRepository_DeleteBlockedSlot_Call) Run(run func(ctx context.Context, id string)) *BlockedSlotRepository_DeleteBlockedSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlockedSlotRepository_DeleteBlockedSlot_Call) Return(_a0 error) *BlockedSlotRepository_DeleteBlockedSlot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BlockedSlotRepository_DeleteBlockedSlot_Call) RunAndReturn(run func(context.Context, string) error) *BlockedSlotRepository_DeleteBlockedSlot_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedSlot provides a mock function with given fields: ctx, id
func (_m *BlockedSlotRepository) GetBlockedSlot(ctx context.Context, id string) (*domain.BlockedSlot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedSlot")
	}

	var r0 *domain.BlockedSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.BlockedSlot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.BlockedSlot); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BlockedSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockedSlotRepository_GetBlockedSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedSlot'
type BlockedSlotRepository_GetBlockedSlot_Call struct {
	*mock.Call
}

// GetBlockedSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *BlockedSlotRepository_Expecter) GetBlockedSlot(ctx interface{}, id interface{}) *BlockedSlotRepository_GetBlockedSlot_Call {
	return &BlockedSlotRepository_GetBlockedSlot_Call{Call: _e.mock.On("GetBlockedSlot", ctx, id)}
}

func (_c *BlockedSlotRepository_GetBlockedSlot_Call) Run(run func(ctx context.Context, id string)) *BlockedSlotRepository_GetBlockedSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *BlockedSlotRepository_GetBlockedSlot_Call) Return(_a0 *domain.BlockedSlot, _a1 error) *BlockedSlotRepository_GetBlockedSlot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockedSlotRepository_GetBlockedSlot_Call) RunAndReturn(run func(context.Context, string) (*domain.BlockedSlot, error)) *BlockedSlotRepository_GetBlockedSlot_Call {
	_c.Call.Return(run)
	return _c
}

// ListBlockedSlots provides a mock function with given fields: ctx, doctorID, from, to
func (_m *BlockedSlotRepository) ListBlockedSlots(ctx context.Context, doctorID string, from time.Time, to time.Time) ([]*domain.BlockedSlot, error) {
	ret := _m.Called(ctx, doctorID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListBlockedSlots")
	}

	var r0 []*domain.BlockedSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]*domain.BlockedSlot, error)); ok {
		return rf(ctx, doctorID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []*domain.BlockedSlot); ok {
		r0 = rf(ctx, doctorID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.BlockedSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, doctorID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockedSlotRepository_ListBlockedSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBlockedSlots'
type BlockedSlotRepository_ListBlockedSlots_Call struct {
	*mock.Call
}

// ListBlockedSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - doctorID string
//   - from time.Time
//   - to time.Time
func (_e *BlockedSlotRepository_Expecter) ListBlockedSlots(ctx interface{}, doctorID interface{}, from interface{}, to interface{}) *BlockedSlotRepository_ListBlockedSlots_Call {
	return &BlockedSlotRepository_ListBlockedSlots_Call{Call: _e.mock.On("ListBlockedSlots", ctx, doctorID, from, to)}
}

func (_c *BlockedSlotRepository_ListBlockedSlots_Call) Run(run func(ctx context.Context, doctorID string, from time.Time, to time.Time)) *BlockedSlotRepository_ListBlockedSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *BlockedSlotRepository_ListBlockedSlots_Call) Return(_a0 []*domain.BlockedSlot, _a1 error) *BlockedSlotRepository_ListBlockedSlots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockedSlotRepository_ListBlockedSlots_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]*domain.BlockedSlot, error)) *BlockedSlotRepository_ListBlockedSlots_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockedSlotRepository creates a new instance of BlockedSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockedSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockedSlotRepository {
	mock := &BlockedSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
