// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "go-challenge-agenda/services/agenda/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// DoctorRepository is an autogenerated mock type for the DoctorRepository type
type DoctorRepository struct {
	mock.Mock
}

type DoctorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DoctorRepository) EXPECT() *DoctorRepository_Expecter {
	return &DoctorRepository_Expecter{mock: &_m.Mock}
}

// GetDoctor provides a mock function with given fields: ctx, id
func (_m *DoctorRepository) GetDoctor(ctx context.Context, id string) (*domain.Doctor, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDoctor")
	}

	var r0 *domain.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Doctor, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Doctor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Doctor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoctorRepository_GetDoctor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDoctor'
type DoctorRepository_GetDoctor_Call struct {
	*mock.Call
}

// GetDoctor is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *DoctorRepository_Expecter) GetDoctor(ctx interface{}, id interface{}) *DoctorRepository_GetDoctor_Call {
	return &DoctorRepository_GetDoctor_Call{Call: _e.mock.On("GetDoctor", ctx, id)}
}

func (_c *DoctorRepository_GetDoctor_Call) Run(run func(ctx context.Context, id string)) *DoctorRepository_GetDoctor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DoctorRepository_GetDoctor_Call) Return(_a0 *domain.Doctor, _a1 error) *DoctorRepository_GetDoctor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DoctorRepository_GetDoctor_Call) RunAndReturn(run func(context.Context, string) (*domain.Doctor, error)) *DoctorRepository_GetDoctor_Call {
	_c.Call.Return(run)
	return _c
}

// ListDoctors provides a mock function with given fields: ctx
func (_m *DoctorRepository) ListDoctors(ctx context.Context) ([]*domain.Doctor, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDoctors")
	}

	var r0 []*domain.Doctor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Doctor, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Doctor); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Doctor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoctorRepository_ListDoctors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDoctors'
type DoctorRepository_ListDoctors_Call struct {
	*mock.Call
}

// ListDoctors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DoctorRepository_Expecter) ListDoctors(ctx interface{}) *DoctorRepository_ListDoctors_Call {
	return &DoctorRepository_ListDoctors_Call{Call: _e.mock.On("ListDoctors", ctx)}
}

func (_c *DoctorRepository_ListDoctors_Call) Run(run func(ctx context.Context)) *DoctorRepository_ListDoctors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DoctorRepository_ListDoctors_Call) Return(_a0 []*domain.Doctor, _a1 error) *DoctorRepository_ListDoctors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DoctorRepository_ListDoctors_Call) RunAndReturn(run func(context.Context) ([]*domain.Doctor, error)) *DoctorRepository_ListDoctors_Call {
	_c.Call.Return(run)
	return _c
}

// NewDoctorRepository creates a new instance of DoctorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDoctorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DoctorRepository {
	mock := &DoctorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
