// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "go-challenge-agenda/services/agenda/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PatientRepository is an autogenerated mock type for the PatientRepository type
type PatientRepository struct {
	mock.Mock
}

type PatientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PatientRepository) EXPECT() *PatientRepository_Expecter {
	return &PatientRepository_Expecter{mock: &_m.Mock}
}

// CreatePatient provides a mock function with given fields: ctx, p
func (_m *PatientRepository) CreatePatient(ctx context.Context, p *domain.Patient) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePatient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Patient) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatientRepository_CreatePatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePatient'
type PatientRepository_CreatePatient_Call struct {
	*mock.Call
}

// CreatePatient is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Patient
func (_e *PatientRepository_Expecter) CreatePatient(ctx interface{}, p interface{}) *PatientRepository_CreatePatient_Call {
	return &PatientRepository_CreatePatient_Call{Call: _e.mock.On("CreatePatient", ctx, p)}
}

func (_c *PatientRepository_CreatePatient_Call) Run(run func(ctx context.Context, p *domain.Patient)) *PatientRepository_CreatePatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Patient))
	})
	return _c
}

func (_c *PatientRepository_CreatePatient_Call) Return(_a0 error) *PatientRepository_CreatePatient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PatientRepository_CreatePatient_Call) RunAndReturn(run func(context.Context, *domain.Patient) error) *PatientRepository_CreatePatient_Call {
	_c.Call.Return(run)
	return _c
}

// GetPatient provides a mock function with given fields: ctx, id
func (_m *PatientRepository) GetPatient(ctx context.Context, id string) (*domain.Patient, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPatient")
	}

	var r0 *domain.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Patient, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Patient); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatientRepository_GetPatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPatient'
type PatientRepository_GetPatient_Call struct {
	*mock.Call
}

// GetPatient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PatientRepository_Expecter) GetPatient(ctx interface{}, id interface{}) *PatientRepository_GetPatient_Call {
	return &PatientRepository_GetPatient_Call{Call: _e.mock.On("GetPatient", ctx, id)}
}

func (_c *PatientRepository_GetPatient_Call) Run(run func(ctx context.Context, id string)) *PatientRepository_GetPatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PatientRepository_GetPatient_Call) Return(_a0 *domain.Patient, _a1 error) *PatientRepository_GetPatient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PatientRepository_GetPatient_Call) RunAndReturn(run func(context.Context, string) (*domain.Patient, error)) *PatientRepository_GetPatient_Call {
	_c.Call.Return(run)
	return _c
}

// GetPatientByPhone provides a mock function with given fields: ctx, phone
func (_m *PatientRepository) GetPatientByPhone(ctx context.Context, phone string) (*domain.Patient, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetPatientByPhone")
	}

	var r0 *domain.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Patient, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Patient); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatientRepository_GetPatientByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPatientByPhone'
type PatientRepository_GetPatientByPhone_Call struct {
	*mock.Call
}

// GetPatientByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *PatientRepository_Expecter) GetPatientByPhone(ctx interface{}, phone interface{}) *PatientRepository_GetPatientByPhone_Call {
	return &PatientRepository_GetPatientByPhone_Call{Call: _e.mock.On("GetPatientByPhone", ctx, phone)}
}

func (_c *PatientRepository_GetPatientByPhone_Call) Run(run func(ctx context.Context, phone string)) *PatientRepository_GetPatientByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PatientRepository_GetPatientByPhone_Call) Return(_a0 *domain.Patient, _a1 error) *PatientRepository_GetPatientByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PatientRepository_GetPatientByPhone_Call) RunAndReturn(run func(context.Context, string) (*domain.Patient, error)) *PatientRepository_GetPatientByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// ListPatients provides a mock function with given fields: ctx
func (_m *PatientRepository) ListPatients(ctx context.Context) ([]*domain.Patient, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPatients")
	}

	var r0 []*domain.Patient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Patient, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Patient); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Patient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatientRepository_ListPatients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPatients'
type PatientRepository_ListPatients_Call struct {
	*mock.Call
}

// ListPatients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PatientRepository_Expecter) ListPatients(ctx interface{}) *PatientRepository_ListPatients_Call {
	return &PatientRepository_ListPatients_Call{Call: _e.mock.On("ListPatients", ctx)}
}

func (_c *PatientRepository_ListPatients_Call) Run(run func(ctx context.Context)) *PatientRepository_ListPatients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PatientRepository_ListPatients_Call) Return(_a0 []*domain.Patient, _a1 error) *PatientRepository_ListPatients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PatientRepository_ListPatients_Call) RunAndReturn(run func(context.Context) ([]*domain.Patient, error)) *PatientRepository_ListPatients_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePatient provides a mock function with given fields: ctx, p
func (_m *PatientRepository) UpdatePatient(ctx context.Context, p *domain.Patient) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePatient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Patient) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatientRepository_UpdatePatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePatient'
type PatientRepository_UpdatePatient_Call struct {
	*mock.Call
}

// UpdatePatient is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Patient
func (_e *PatientRepository_Expecter) UpdatePatient(ctx interface{}, p interface{}) *PatientRepository_UpdatePatient_Call {
	return &PatientRepository_UpdatePatient_Call{Call: _e.mock.On("UpdatePatient", ctx, p)}
}

func (_c *PatientRepository_UpdatePatient_Call) Run(run func(ctx context.Context, p *domain.Patient)) *PatientRepository_UpdatePatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Patient))
	})
	return _c
}

func (_c *PatientRepository_UpdatePatient_Call) Return(_a0 error) *PatientRepository_UpdatePatient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PatientRepository_UpdatePatient_Call) RunAndReturn(run func(context.Context, *domain.Patient) error) *PatientRepository_UpdatePatient_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePatient provides a mock function with given fields: ctx, id
func (_m *PatientRepository) DeletePatient(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePatient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatientRepository_DeletePatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePatient'
type PatientRepository_DeletePatient_Call struct {
	*mock.Call
}

// DeletePatient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PatientRepository_Expecter) DeletePatient(ctx interface{}, id interface{}) *PatientRepository_DeletePatient_Call {
	return &PatientRepository_DeletePatient_Call{Call: _e.mock.On("DeletePatient", ctx, id)}
}

func (_c *PatientRepository_DeletePatient_Call) Run(run func(ctx context.Context, id string)) *PatientRepository_DeletePatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PatientRepository_DeletePatient_Call) Return(_a0 error) *PatientRepository_DeletePatient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PatientRepository_DeletePatient_Call) RunAndReturn(run func(context.Context, string) error) *PatientRepository_DeletePatient_Call {
	_c.Call.Return(run)
	return _c
}

// NewPatientRepository creates a new instance of PatientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPatientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PatientRepository {
	mock := &PatientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
